name: Workflow Filters and Activities

on:
    workflow_dispatch: 
    schedule:
        - cron: "*/59 * * * *"
    push:
        branches: 
            - main
            - '!feature/*'
    pull_request:
        types: 
            - opened
            - closed
        paths-ignore: 
            - README.md
        branches: 
            - main

jobs:
    workflow-hello-with-event-time:
        runs-on: ubuntu-latest
        steps:
            - run: echo this workflow/job/step is executed for the event type - ${{github.event_path}}
            - run: cat /home/runner/work/_temp/_github_workflow/event.json
